### ISSUE TITLE
Add ageOfInformation field to API response

### ISSUE THREAD

**Issue by eric-murray** [camaraproject/DeviceIdentifier#47]
**Problem description**
Current API response gives no indication of when the physical device information was collected for the specified subscription identifier (e.g. `phoneNumber`). Dependent on the backend implementation, this information could have been collected some time earlier, and potentially be out of date

**Possible evolution**
Add an `ageOfInfomation` field to the response. Time unit TBD, but probably "hours" is sufficient. For "real-time" systems (for example, getting the IMEI information from the PCRF), the age would be 0.

**Alternative solution**
None proposed

**Additional context**
None

**Comment by Kevsy** [comment]
LGTM, but I guess that's a typo:

> `Add an ageOfInfomation field to the response`

**Comment by HuubAppelboom** [comment]
Hours would be sufficient, it doesn't need to be that precise. Important to know is whether the user (fraudster) could have been putting the SIM in another device.

**Comment by eric-murray** [comment]
Following discussion in last meeting proposal is to introduce `lastChecked` response parameter, defined as follows:
```
lastChecked: 
  description: Last time that the associated device identity was checked and updated if necessary
  type: string
  format: date-time
```
